hw-3
little-plumelet/kts-hw-3 pull request #1
Opened 2023-09-09 16:14 UTC by little-plumelet

2023-09-12 09:00 UTC, nikkov13 requested changes

2023-09-12 09:00 UTC, nikkov13 commented on src/configs/RecipeInterface.ts
> +}
Все кроме constants в этой директории не относится к конфигу и должно храниться в директории types или entities. Для каждой сущности свой файл, и какие-то базовые типы можно объединить в один файл common

2023-09-12 09:00 UTC, nikkov13 commented on src/configs/mealType.ts
> +  'main course' = 'main course',
В енамах ключи не должны содержать пробелы, пишем кэмел-кейсом, кавычки убираем
```suggestion
  mainCourse = 'main course',
```

2023-09-12 09:00 UTC, nikkov13 commented on src/styles/index.css
> +  --brand: #B5460F;
Обычно используем scss переменные и выносим переменные по разным файлам в зависимости от типа, например colors, gaps, typography итд. в индексе должны быть только базовые типы

2023-09-12 09:00 UTC, nikkov13 commented on src/App.tsx
> +        <Route path="*" element={<Navigate to="/" replace />} />
Пути лучше выносить в конфиг (config/urls), так у тебя будет один источник и для роутов и для ссылок в проекте

2023-09-12 09:00 UTC, nikkov13 commented on src/main.tsx
> +import './styles/index.css';
Импорт стилей дожен идти последним

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/SearchInput/SearchInput.tsx
> +interface ISearchInputProps {
interface используем для типизации классов, тут уместнее будет использовать type, надо поправить везде по проекту

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/Home.tsx
> +export const Home = () => {
Типизация
```suggestion
export const Home: React.FC = () => {
```

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/Home.tsx
> +      <Header />
Этот хедер используется на всех страницах, лучше вынести его наверх, например создать компонент Root, в нем будут провайдеры, роуты и компоненты которые отображаются независимо от того, на какой странице мы находимся

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/Banner.tsx
> +    <section className={cn(styles.homeMainImage)}>
Используется только один класс, classnames не нужен в таком случае. Но вообще, лучше в пропсах принимать classNames и добавить его сюда, чтобы можно было управлять положением компонента на странице снаружи

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/Banner.tsx
> +      <p className={cn(styles.homeMainImageTitle)}>Be inspired, find your own recipe</p>
Аналогично, cn не нужен, надо проверить и поправить везде на проекте

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/styles.module.scss
> +.homeMainImage {
имена классов пишем кебаб-кейсом, а уже в компонентах можно для обращения к классам использовать кэмэл-кейс
```suggestion
.home-main-image {
```

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/styles.module.scss
> +  &Title {
Именуем классы по БЭМу, parent__child_mod
```suggestion
  &__Title {
```

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/styles.module.scss
> +  background-color: #d3d3d3;
Все цвета надо вынести в scss-переменные

2023-09-12 09:00 UTC, nikkov13 commented on src/pages/Home/components/Banner/styles.module.scss
> +    font-size: 48px;
Размеры шрифтов тоже лучше вынести в переменные. Вообще для текстов можно создать компонент Typo, который будет принимать пропсом тип текста (например h1, h2, textReg, textBold итд) и цвет и внутри управлять отображением

2023-09-12 09:37 UTC, nikkov13 commented on src/components/Button/Button.tsx
> +      {loading && <Loader size="s" className={styles.loader} />}
Должен показываться либо лоадер, либо children

2023-09-12 09:37 UTC, nikkov13 commented on src/components/Button/style.module.scss
> +  padding: var(--space-s) var(--space-l);
Используем scss переменные

2023-09-12 09:39 UTC, nikkov13 commented on src/components/Card/styles.module.scss
> +  gap: var(--space-xl, 24px);
gap нестабильно работает с флексами, лучше использовать только с гридами

2023-09-12 09:41 UTC, nikkov13 commented on src/components/CardList/CardList.tsx
> +export const CardList: React.FC<{ cards: Array<CardProps> }> = ({ cards }) => {
Лучше выносить типы пропсов наружу
```suggestion
type CardListProps = {
  cards: CardProps[];
};

export const CardList: React.FC<CardListProps> = ({ cards }) => {
```

2023-09-12 09:41 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +    <header className={cn(styles.header)}>
Не нужен cn, когда только 1 класс, проверь и поправь по всему проекту

2023-09-12 09:44 UTC, nikkov13 commented on src/components/Input/Input.tsx
> +  afterSlot?: React.ReactNode;
Если проп для иконки, можно более точно определить тип, например: Icon: FC<IconProps>. И дальше Использовать как <Icon ... />

2023-09-12 09:46 UTC, nikkov13 commented on src/components/Loader/Loader.tsx
> +type sizeType = 's' | 'm' | 'l';
для таких перечислений используем enum. Все типы и енамы именуем с заглавной буквы
```suggestion
enum SizeType = {
  s = 's',
  m = 'm',
  l = 'l',
}
```

2023-09-12 09:48 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +  const [isOpen, setIsOpen] = React.useState(false);
можно вынести в кастом хук, который будет возвращать { isOpen, open, close }

2023-09-12 09:55 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +    const currentValue = (event.target as HTMLLIElement).innerHTML;
Лучше так не делать, брать значение из innerHTML не надежно да и выглядит костыльно.
В данном случае надо для опций сделать отдельный компонент Option, который будет хранить в себе id и title и принипать пропсом функцию onSelect и отдавать этот самый стилизованный li. Внутри этот компонент будет вызывать onSelect(id, value) по клику и обрабатывать event и что-то из него вытаскивать нам вообще не придется

2023-09-12 09:57 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +    const currentKey = (event.target as HTMLLIElement).id;
```suggestion
  function selectOption(id: number, value: string) {
    const currentValue = value;
    const currentKey = id;
```

2023-09-12 09:58 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +            </li>
```suggestion
            <Option
              key={option.key}
              onSelect={selectOption}
              id={option.key}
              value={option.value}
              className={cn(styles.option, {
                [styles.selected]: value.find((el) => el.key === option.key),
              })}
            />
```

2023-09-12 09:59 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +  view?: 'title' | 'button' | 'p-20' | 'p-18' | 'p-16' | 'p-14';
Это должно быть вынесено в enum

2023-09-12 09:59 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +  tag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'div' | 'p' | 'span';
Аналогично

2023-09-12 09:59 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +  weight?: 'normal' | 'medium' | 'bold';
аналогично

2023-09-12 09:59 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +  color?: 'primary' | 'secondary' | 'accent';
И тут

2023-09-12 10:04 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +      style={{
Стили, которые не зависят от переменных, надо уносить в класс

2023-09-12 10:06 UTC, nikkov13 commented on src/configs/RecipeInterface.ts
> +export interface IRecipeData {
interface используем для типизации классов, для всего остального используем type. В этом дз не пишем сторы, так что интерфейсов быть не должно в принципе

2023-09-12 10:06 UTC, nikkov13 commented on src/configs/RecipeInterface.ts
> +    nutrients: Array<INutrient>;
Везде лечше так

```suggestion
    nutrients: INutrient[];
```

2023-09-12 10:07 UTC, nikkov13 commented on src/configs/mealType.ts
> +export type MealType = 'main course' | 'side dish' | 'dessert' | '';
Зачем это??

2023-09-12 10:08 UTC, nikkov13 commented on src/pages/Home/components/RecipeList/RecipeList.tsx
> +  const queryNb = 9;
Это можно вынести из компонента в константу

2023-09-12 10:10 UTC, nikkov13 commented on src/pages/Home/components/RecipeList/RecipeList.tsx
> +          throw Error('Unknown error occurred');
лучше не дропать так ошибки, потому что у тебя упадет приложение и пользователь просто не поймет почему и что делать. Если получаешь ошибку в запросе, показываешь плейсхолжер вместо контента с предложением перезагрузить страницу или попробовать позже + можно отправлять логи куда-то типа centry, но это уже сейчас делать не обязательно

2023-09-12 10:11 UTC, nikkov13 commented on src/pages/Home/components/RecipeList/utils.tsx
> +type recipeProps = Pick<IRecipeData, 'id' | 'title' | 'readyInMinutes' | 'image' | 'nutrition'>;
Типы с заглавной буквы

2023-09-12 10:14 UTC, nikkov13 commented on src/pages/Home/components/RecipeList/utils.tsx
> +      }) as unknown as CardProps & { key: string },
Так делать нельзя никогда.
По сути так убиваются все преимущества типизации, ты не имеешь никакого представления, что придет из функции. Надо выписать тип, который будет возвращать функция и явно его указать. Выпадут ошибки: надо понять что не так и решить это БЕЗ кастов, тем более таких.

2023-09-12 10:16 UTC, nikkov13 commented on src/pages/Home/components/RecipeList/utils.tsx
> +          <Text color="accent" maxLines={1}>
Лучше не хранить так реакт элементы, а хранить примитивы (в данном случае просто ссылку или просто текст).
А базовую карточку в случае если у нас несколько разных вариантов карточек, мы расширяем в другом компоненте, который принимает эти примитивные пропсы и внутри себя передает в базовую карточку нужные элементы

2023-09-12 10:16 UTC, nikkov13 commented on src/pages/Home/components/SearchInput/SearchInput.tsx
> +  onClick: React.MouseEventHandler<HTMLButtonElement>;
Как правило можно использовать VoidFunction, если не надо взаимодействовать с event объектом

2023-09-12 10:18 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +          throw Error('Unknown error occurred');
Аналогично комменту про ошибки на другой странице

2023-09-12 10:20 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +        <Loader size="l" className={styles.loader} />
должен быть enum LoaderSize = { s = 's', ... } и тут используем <Loader size={LoaderSize.s} ... />
Так при изменении значения тебе не нужно будет менять их по всему проекту, а можно будет изменить только в одном енаме

2023-09-12 10:21 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +        <Text view="title">{data?.title}</Text>
У тебя вся страница зависит от наличия data. Лучше поставить в начале одну проверку data && !loading и дальше убрать все проверки на наличие data, а если data === null отобразать плейсхолдер

2023-09-12 10:22 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +      <section className={styles.compositionSection}>
Очень уж крупный получается компонент, лучше разбить его хотя бы по секциям

2023-09-12 10:23 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +@mixin commonSection {
Все миксины мы выносим в отдельный файл styles/mixins.scss и импортируем оттуда

2023-09-12 10:24 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +  align-content: center;
Это можно вынести в миксин flex-center
Миксины именуем кебаб-кейсом

2023-09-12 10:25 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +    order: -1;
```suggestion
  &:first-child {
    order: -1;
    }
```

2023-09-12 10:25 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +  }
```suggestion
  &Part {
    width: 100%;
  }

  &Part:first-child {
    order: -1;
  }
```
```suggestion
  &Part {
    width: 100%;
    
    &:first-child {
      order: -1;
    }
  }
```

2023-09-12 10:51 UTC, little-plumelet commented on src/pages/Home/components/RecipeList/utils.tsx
> +      }) as unknown as CardProps & { key: string },
done

2023-09-12 11:01 UTC, little-plumelet commented on src/configs/RecipeInterface.ts
> +}
done

2023-09-12 11:01 UTC, little-plumelet commented on src/configs/mealType.ts
> +  'main course' = 'main course',
done

2023-09-12 11:04 UTC, little-plumelet commented on src/configs/RecipeInterface.ts
> +export interface IRecipeData {
fixed

2023-09-12 11:04 UTC, little-plumelet commented on src/configs/RecipeInterface.ts
> +    nutrients: Array<INutrient>;
ok

2023-09-12 11:04 UTC, little-plumelet commented on src/configs/mealType.ts
> +export type MealType = 'main course' | 'side dish' | 'dessert' | '';
deleted

2023-09-12 11:09 UTC, little-plumelet commented on src/pages/Home/components/RecipeList/utils.tsx
> +type recipeProps = Pick<IRecipeData, 'id' | 'title' | 'readyInMinutes' | 'image' | 'nutrition'>;
done

2023-09-12 11:11 UTC, little-plumelet commented on src/main.tsx
> +import './styles/index.css';
done

2023-09-12 11:13 UTC, little-plumelet commented on src/pages/Home/components/SearchInput/SearchInput.tsx
> +interface ISearchInputProps {
done

2023-09-12 11:14 UTC, little-plumelet commented on src/pages/Home/Home.tsx
> +export const Home = () => {
done

2023-09-12 11:56 UTC, little-plumelet commented on src/styles/index.css
> +  --brand: #B5460F;
done

2023-09-12 11:57 UTC, little-plumelet commented on src/components/Button/style.module.scss
> +  padding: var(--space-s) var(--space-l);
done

2023-09-12 12:53 UTC, little-plumelet commented on src/pages/Home/components/Banner/styles.module.scss
> +  background-color: #d3d3d3;
done

2023-09-12 12:53 UTC, little-plumelet commented on src/pages/Home/components/Banner/styles.module.scss
> +    font-size: 48px;
есть компонент Text - надо его до конца настроить

2023-09-12 12:58 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +      style={{
done

2023-09-12 13:02 UTC, little-plumelet commented on src/components/CardList/CardList.tsx
> +export const CardList: React.FC<{ cards: Array<CardProps> }> = ({ cards }) => {
done

2023-09-12 13:26 UTC, little-plumelet commented on src/components/MultiDropdown/MultiDropdown.tsx
> +            </li>
done

2023-09-13 07:47 UTC, little-plumelet commented on src/pages/Home/components/RecipeList/utils.tsx
> +          <Text color="accent" maxLines={1}>
done

2023-09-13 07:52 UTC, little-plumelet commented on src/pages/Home/components/SearchInput/SearchInput.tsx
> +  onClick: React.MouseEventHandler<HTMLButtonElement>;
done

2023-09-13 07:52 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +@mixin commonSection {
done

2023-09-13 08:42 UTC, little-plumelet commented on src/pages/Home/Home.tsx
> +      <Header />
done

2023-09-13 08:42 UTC, little-plumelet commented on src/App.tsx
> +        <Route path="*" element={<Navigate to="/" replace />} />
done

2023-09-13 09:03 UTC, little-plumelet commented on src/pages/Home/components/Banner/Banner.tsx
> +    <section className={cn(styles.homeMainImage)}>
done

2023-09-13 09:03 UTC, little-plumelet commented on src/pages/Home/components/Banner/Banner.tsx
> +      <p className={cn(styles.homeMainImageTitle)}>Be inspired, find your own recipe</p>
done

2023-09-13 09:53 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +  }
done

2023-09-13 09:54 UTC, little-plumelet commented on src/components/MultiDropdown/MultiDropdown.tsx
> +    const currentValue = (event.target as HTMLLIElement).innerHTML;
fixed

2023-09-13 09:54 UTC, little-plumelet commented on src/components/Header/Header.tsx
> +    <header className={cn(styles.header)}>
done

2023-09-13 09:54 UTC, little-plumelet commented on src/pages/Home/components/Banner/styles.module.scss
> +  &Title {
done

2023-09-13 09:56 UTC, little-plumelet commented on src/pages/Home/components/Banner/styles.module.scss
> +.homeMainImage {
Почему-то в компоненте к классам стилей нельзя обращаться в кэмелкейсе если в файле со стилями классы прописаны через дефис. Приходится в компонентах писать styles['home-main-image'];

2023-09-13 09:58 UTC, little-plumelet commented on src/components/Button/Button.tsx
> +      {loading && <Loader size="s" className={styles.loader} />}
done

2023-09-13 10:30 UTC, little-plumelet commented on src/components/Card/styles.module.scss
> +  gap: var(--space-xl, 24px);
fixed

2023-09-13 14:26 UTC, little-plumelet commented on src/components/Loader/Loader.tsx
> +type sizeType = 's' | 'm' | 'l';
done

2023-09-13 14:38 UTC, little-plumelet commented on src/components/MultiDropdown/MultiDropdown.tsx
> +  const [isOpen, setIsOpen] = React.useState(false);
done

2023-09-13 14:39 UTC, little-plumelet commented on src/components/MultiDropdown/MultiDropdown.tsx
> +    const currentKey = (event.target as HTMLLIElement).id;
done

2023-09-13 14:49 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +  view?: 'title' | 'button' | 'p-20' | 'p-18' | 'p-16' | 'p-14';
done

2023-09-13 14:49 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +  tag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'div' | 'p' | 'span';
done

2023-09-13 14:55 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +  weight?: 'normal' | 'medium' | 'bold';
done

2023-09-13 14:55 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +  color?: 'primary' | 'secondary' | 'accent';
done

2023-09-13 14:58 UTC, little-plumelet commented on src/pages/Home/components/RecipeList/RecipeList.tsx
> +  const queryNb = 9;
done

2023-09-13 15:56 UTC, little-plumelet commented on src/pages/Home/components/RecipeList/RecipeList.tsx
> +          throw Error('Unknown error occurred');
добавила компонент ErrorCp чтобы показывать если случилась ошибка

2023-09-13 15:56 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +          throw Error('Unknown error occurred');
fixed

2023-09-13 15:56 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +        <Loader size="l" className={styles.loader} />
done

2023-09-13 16:01 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +        <Text view="title">{data?.title}</Text>
done

2023-09-14 09:31 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/RecipeCard.tsx
> +      <section className={styles.compositionSection}>
done

2023-09-14 11:49 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeCard/styles.module.scss
> +  align-content: center;
done

2023-09-14 11:50 UTC, little-plumelet commented on src/components/Input/Input.tsx
> +  afterSlot?: React.ReactNode;
пока мне неудобно так делать

2023-09-15 17:23 UTC, nikkov13 commented on src/components/icons/ArrowDownIcon/ArrowDownIcon.tsx
> +const ArrowDownIcon: React.FC<IconProps> = ({ color = 'primary', className, ...props }) => {
У тебя тип для color это енам, соответственно ты можешь передать в этот проп только значение из енама.
По идее тебе линтер должен ошибки выводить во всех таких местах. Надо пройти по всему проекту и поправить везде, где вместо значения из какого-либо енама (не только цвет) передается строка
```suggestion
const ArrowDownIcon: React.FC<IconProps> = ({ color = ColorType.primary, className, ...props }) => {
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Button/Button.tsx
> +      {!loading && children}
```suggestion
      {loading ? <Loader size="s" className={styles.loader} /> : children}
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/CardList/CardList.tsx
> +            <Link to={`${URLS.recipe + '/' + card.id}`} style={{ textDecoration: 'none' }}>
Лучше в URLS хранить не просто строку в данном случае, а функцию, которая будет принимать id и возвращать готовый урл
```suggestion
          actionSlot={
            <Link to={`${URLS.recipe.create(card.id)}`} style={{ textDecoration: 'none' }}>
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/CardList/CardList.tsx
> +          key={card.id.toString()}
Не надо указывать key в типе пропсов компонента и тогда не придется преобразовывать его в строку

2023-09-15 17:23 UTC, nikkov13 commented on src/components/ErrorCp/ErrorCp.tsx
> +        {location.pathname !== URLS['/'] && (
для этого есть хук useMatch в react-router

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +          height="60px"
```suggestion
          width="60"
          height="60"
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +        <svg
Это надо в отдельный компонент Logo, в этой же директории рядышком положить

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +        <NavLink to={URLS['/']} className={({ isActive }) => cn(isActive ? styles.active : styles.pending, styles.nav)}>
надо назвать это как-нибудь типа root и обращаться urls.root.
urls не должен быть енамом, это должен быть обычный объект, у него может быть вложенность, например тебе может понадобиться для одной страницы маска, которую ты будешь передавать в роут и функция-креатор, которой ты будешь генерировать урл по id для подстановки в ссылку, тогда это будет выглядеть примерно так
```
urls = {
  root: '/',
  recipe: {
    mask: '/recipe/:id',
    create: (id: number | string) => `/recipe/${id}`,
}
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +        <AccountIcon color="accent" className={styles['icon-block']} />
Везде надо поправить
```suggestion
        <AccountIcon color={ColorType.accent} className={styles['icon-block']} />
```

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +              </div>
Это надо вынести в отдельный компонент, который будет хранить свой номер страницы и получать текущую страницу, сам внутри сравнивать и управлять своими стилями

2023-09-15 17:23 UTC, nikkov13 commented on src/components/Text/Text.tsx
> +      className={cn(styles[view ?? ''], className, styles[color ?? ''], styles.common)}
Лучше при деструктуризации пропсов присвоить дефолтные значения для view и color, так мы избежим лишних проверок и будет более прозрачно, какие значения будут, если не прокинуть эти пропсы

2023-09-15 17:23 UTC, nikkov13 commented on src/configs/urls.ts
> +export enum URLS {
Это должно быть объектом, выше оставлял подробный коммент

2023-09-15 17:23 UTC, nikkov13 commented on src/pages/Recipe/Recipe.tsx
> +  );
Здесь один компонент лишний кажется
```suggestion
  return <RecipeCard />;
```

2023-09-15 17:23 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeBasicInfo/RecipeBasicInfo.tsx
> +          <div className={styles['basic-info-section']}>
Выглядит, как будто info-section надо вынести в компонент, очень часто повторяется один и тот же код

2023-09-15 17:23 UTC, nikkov13 commented on src/pages/Recipe/components/RecipeDescription/RecipeDescription.tsx
> +      <div className={styles.description} dangerouslySetInnerHTML={{ __html: description ?? '' }}></div>
У тебя все еще не чистится эта строка, это **ВАЖНО**

2023-09-15 17:23 UTC, nikkov13 commented on src/types/MealMap.ts
> +  'mainCourse' = 'main course',
Кавычки не нужны, поправь везде

2023-09-17 09:53 UTC, little-plumelet commented on src/components/icons/ArrowDownIcon/ArrowDownIcon.tsx
> +const ArrowDownIcon: React.FC<IconProps> = ({ color = 'primary', className, ...props }) => {
done

2023-09-17 09:56 UTC, little-plumelet commented on src/components/Button/Button.tsx
> +      {!loading && children}
done

2023-09-17 10:03 UTC, little-plumelet commented on src/components/Header/Header.tsx
> +        <NavLink to={URLS['/']} className={({ isActive }) => cn(isActive ? styles.active : styles.pending, styles.nav)}>
done

2023-09-17 10:03 UTC, little-plumelet commented on src/components/Header/Header.tsx
> +        <AccountIcon color="accent" className={styles['icon-block']} />
done

2023-09-17 10:03 UTC, little-plumelet commented on src/components/CardList/CardList.tsx
> +            <Link to={`${URLS.recipe + '/' + card.id}`} style={{ textDecoration: 'none' }}>
done

2023-09-17 10:04 UTC, little-plumelet commented on src/configs/urls.ts
> +export enum URLS {
done

2023-09-17 10:10 UTC, little-plumelet commented on src/components/ErrorCp/ErrorCp.tsx
> +        {location.pathname !== URLS['/'] && (
done

2023-09-17 10:14 UTC, little-plumelet commented on src/components/CardList/CardList.tsx
> +          key={card.id.toString()}
done

2023-09-17 10:18 UTC, little-plumelet commented on src/components/Header/Header.tsx
> +          height="60px"
done

2023-09-17 10:23 UTC, little-plumelet commented on src/components/Header/Header.tsx
> +        <svg
done

2023-09-17 10:50 UTC, little-plumelet commented on src/components/Pagination/Pagination.tsx
> +              </div>
done

2023-09-17 10:53 UTC, little-plumelet commented on src/components/Text/Text.tsx
> +      className={cn(styles[view ?? ''], className, styles[color ?? ''], styles.common)}
done

2023-09-17 10:53 UTC, little-plumelet commented on src/pages/Recipe/Recipe.tsx
> +  );
done

2023-09-17 11:09 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeBasicInfo/RecipeBasicInfo.tsx
> +          <div className={styles['basic-info-section']}>
done

2023-09-17 11:17 UTC, little-plumelet commented on src/pages/Recipe/components/RecipeDescription/RecipeDescription.tsx
> +      <div className={styles.description} dangerouslySetInnerHTML={{ __html: description ?? '' }}></div>
К сожалению эта строка хранится в API c html тегами и если вставлять ее как обычную строку то теги будут прописываться как обычный текст. Именно поэтому я здесь использую вставку dangerouslySetInnerHTML.
Пример как выглядит строка в базе - "This lacto ovo vegetarian recipe has <b>557 calories</b>, <b>16g of protein</b>, and <b>42g of fat</b> per serving. For <b>$2.79 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. This recipe is liked by 1 foodies and cooks. A mixture of walnuts, bell pepper, creamy gorgonzola, and a handful of other ingredients are all it takes to make this recipe so tasty. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 75%</b>. This score is pretty good. If you like this recipe, you might also like recipes such as <a href=\"https://spoonacular.com/recipes/spring-salad-with-gorgonzola-and-walnuts-122928\">Spring Salad With Gorgonzolan and Walnuts</a>, <a href=\"https://spoonacular.com/recipes/endive-salad-with-walnuts-pears-and-gorgonzola-157059\">Endive Salad with Walnuts, Pears, and Gorgonzola</a>, and <a href=\"https://spoonacular.com/recipes/escarole-and-endive-salad-with-gorgonzola-and-walnuts-12833\">Escarole And Endive Salad With Gorgonzolan And Walnuts</a>."

2023-09-17 11:25 UTC, little-plumelet commented on src/types/MealMap.ts
> +  'mainCourse' = 'main course',
done

2023-09-17 11:26 UTC, merged